# load_setup_py_data is a function provided by
# the conda-build infrastructure which loads all
# of the metadata specified in setup.py
{% set data = load_setup_py_data() %}
package:
  name:    fsl_mrs
  version: {{ data['version'] }}

build:
  # Identifies this as a pure-python package
  noarch: python

  # The standard distutils/setuptools
  # infrastructure is used to build
  # the python package
  script: python setup.py install --single-version-externally-managed --record=record.txt


source:
  path: ../

# Python requirements (ones which are available under
# the same name on both PyPi and defaults/conda-forge)
# are ingested from those listed in setup.py.
#
# Non-python/platform-specific/FSL-specific
# requirements may additionally be listed here.
requirements:
  build:
    - python >=3.9
    - setuptools
    {% for package in data.get('setup_requires', {}) %}
    - {{ package.lower() }}
    {% endfor %}
  run:
    - python >=3.9
    {% for package in data.get('install_requires', {}) %}
    - {{ package.lower() }}
    {% endfor %}
    {% for name, pkgs in data.get('extras_require', dict()).items() %}
    {% for package in pkgs %}
    - {{ package.lower() }}
    {% endfor %}
    {% endfor %}
